services:
  database:
    image: "postgres:latest"
    # change to expose when using nginx
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql
    networks:
      - my-bridge

  {{cookiecutter.project_name}}-backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: {{cookiecutter.project_name}}-backend
    # change to expose when using nginx
    ports:
      - "${BACKEND_PORT}:8000"
    networks:
      - my-bridge
    depends_on:
      - database
    environment:
      PGHOST: database
      PGPORT: ${POSTGRES_PORT}
      PGDATABASE: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
    command: bash -c "gunicorn --bind 0.0.0.0:8000 api.wsgi"

  {{cookiecutter.project_name}}-frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: {{cookiecutter.project_name}}-frontend
    # change to expose when using nginx
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - my-bridge
    depends_on:
      - {{cookiecutter.project_name}}-backend

  # Only used for https protection
  nginx:
    image: nginx:latest
    ports:
      - ${NGINX_HTTPS_PORT}:443
      - ${NGINX_HTTP_PORT}:80
    volumes:
      - ${NGINX_VOLUME}/nginx/conf/default.conf:/etc/nginx/nginx.conf:ro
      - ${NGINX_VOLUME}/nginx/ssl/:/etc/nginx/certs:ro
    depends_on:
      - {{cookiecutter.project_name}}-frontend

networks:
  my-bridge:
    driver: bridge
