name: Build Deploy Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Gitea Registry
        uses: docker/login-action@v3
        with:
          registry: https://gitea.anbykatz.me
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_LOGIN_TOKEN }}
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Backend
        uses: docker/build-push-action@v6
        with:
          file: ./docker/backend/Dockerfile
          push: true
          tags: gitea.anbykatz.me/atheni/{{cookiecutter.project_name}}-frontend:latest
          platforms: linux/amd64,linux/arm64
      - name: Build Frontend
        uses: docker/build-push-action@v6
        with:
          file: ./docker/frontend/Dockerfile
          push: true
          tags: gitea.anbykatz.me/atheni/{{cookiecutter.project_name}}-backend:latest
          platforms: linux/amd64,linux/arm64
